### PR TITLE
IC-14: Create Post API

### PR DESCRIPTION
**Pull request by sobuse**
* created controller
* created dto class

### CODE REVIEW

**Comment by sobuse** [comment]
I have been able to test my pay load because I was running into this error below

image

**Comment by ehimah** [comment]
okay but you're supposed to test this from Postman right?

**Comment by sobuse** [comment]
Yes

**Comment by sobuse** [comment]
Yes

**Comment by ehimah** [comment]
> Yes

can you post the error from postman? Try and test it in postman still, and see. if you have an error.

**Comment by sobuse** [comment]
I tried it like that and  I was getting a 404 error response also I could not hit the end point because the URL was not the same on my web page as what I was testing against in post man . my web page  URL is //localhost:7217 and on my post man https://localhost:7217,
I also tried editing the URL on my post man to match the URL  on my web page it still did not work.

**Comment by ehimah** [comment]
> I tried it like that and I was getting a 404 error response also I could not hit the end point because the URL was not the same on my web page as what I was testing against in post man . my web page URL is //localhost:7217 and on my post man https://localhost:7217, I also tried editing the URL on my post man to match the URL on my web page it still did not work.

with a URL of https://localhost:7217/ why is the controller/action not specified here? Can you share the full URL being used in your postman?

**Review by ehimah — APPROVED** [review]

**Pull request merged**
